"""First: Create Tables

Revision ID: 0893dc289ca0
Revises:
Create Date: 2025-10-31 02:52:08.668177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0893dc289ca0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_ProductTypes',
    sa.Column('prodtype_id', sa.UUID(), nullable=False),
    sa.Column('prodtype_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('prodtype_id')
    )
    op.create_table('T_Users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_login', sa.String(), nullable=False),
    sa.Column('user_password', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('T_Orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['T_Users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('T_Products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_thumbnail', sa.String(), nullable=True),
    sa.Column('product_type', sa.UUID(), nullable=True),
    sa.Column('product_desc', sa.String(), nullable=True),
    sa.Column('product_rating', sa.Float(), nullable=True),
    sa.Column('product_barcode', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['product_type'], ['T_ProductTypes.prodtype_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('T_OrdersProducts',
    sa.Column('order_product_id', sa.UUID(), nullable=False),
    sa.Column('id_order', sa.UUID(), nullable=False),
    sa.Column('id_product', sa.UUID(), nullable=False),
    sa.Column('product_date_start', sa.Date(), nullable=True),
    sa.Column('product_date_end', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_order'], ['T_Orders.order_id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['T_Products.product_id'], ),
    sa.PrimaryKeyConstraint('order_product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T_OrdersProducts')
    op.drop_table('T_Products')
    op.drop_table('T_Orders')
    op.drop_table('T_Users')
    op.drop_table('T_ProductTypes')
    # ### end Alembic commands ###
