"""Initial revision

Revision ID: ee818522555a
Revises: 
Create Date: 2025-10-15 16:22:08.054247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee818522555a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK_Orders_Users'), 'T_Orders', type_='foreignkey')
    op.create_foreign_key(None, 'T_Orders', 'T_Users', ['id_user'], ['user_id'])
    op.drop_constraint(op.f('FK_OrdersProducts_Orders'), 'T_OrdersProducts', type_='foreignkey')
    op.drop_constraint(op.f('FK_OrdersProducts_Products'), 'T_OrdersProducts', type_='foreignkey')
    op.create_foreign_key(None, 'T_OrdersProducts', 'T_Products', ['id_product'], ['product_id'])
    op.create_foreign_key(None, 'T_OrdersProducts', 'T_Orders', ['id_order'], ['order_id'])
    op.alter_column('T_ProductTypes', 'prodtype_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('T_Products', 'product_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint(op.f('FK_Products_ProductTypes'), 'T_Products', type_='foreignkey')
    op.create_foreign_key(None, 'T_Products', 'T_ProductTypes', ['product_type'], ['prodtype_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'T_Products', type_='foreignkey')
    op.create_foreign_key(op.f('FK_Products_ProductTypes'), 'T_Products', 'T_ProductTypes', ['product_type'], ['prodtype_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('T_Products', 'product_rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('T_ProductTypes', 'prodtype_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'T_OrdersProducts', type_='foreignkey')
    op.drop_constraint(None, 'T_OrdersProducts', type_='foreignkey')
    op.create_foreign_key(op.f('FK_OrdersProducts_Products'), 'T_OrdersProducts', 'T_Products', ['id_product'], ['product_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('FK_OrdersProducts_Orders'), 'T_OrdersProducts', 'T_Orders', ['id_order'], ['order_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'T_Orders', type_='foreignkey')
    op.create_foreign_key(op.f('FK_Orders_Users'), 'T_Orders', 'T_Users', ['id_user'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
